name: ML Pipeline

on:
  push:

jobs:
  train:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install pandas scikit-learn

    - name: Train Model
      run: python src/train.py

    - name: Upload metrics
      uses: actions/upload-artifact@v4
      with:
        name: metrics
        path: metrics.json